[project]
name = "repetitive-neural-nonsense"
description = "Ekstra Bladet RecSys Challenge 2024"
version = "0.0.1"
authors = [
    { name = "Yahya Jabary"},
    { name = "Johannes Kruse", email = "johannes.kruse@eb.dk" },
]
requires-python = ">=3.10, <3.12"

[tool.black]
line-length = 200
